# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'person.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\rpersonservice\"M\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0b\n\x03sex\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\"<\n\x13\x43reatePersonRequest\x12%\n\x06person\x18\x01 \x01(\x0b\x32\x15.personservice.Person\"=\n\x14\x43reatePersonResponse\x12%\n\x06person\x18\x01 \x01(\x0b\x32\x15.personservice.Person\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x11GetPersonResponse\x12%\n\x06person\x18\x01 \x01(\x0b\x32\x15.personservice.Person\"<\n\x13UpdatePersonRequest\x12%\n\x06person\x18\x01 \x01(\x0b\x32\x15.personservice.Person\"=\n\x14UpdatePersonResponse\x12%\n\x06person\x18\x01 \x01(\x0b\x32\x15.personservice.Person\"!\n\x13\x44\x65letePersonRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x44\x65letePersonResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd5\x02\n\rPersonService\x12Q\n\x06\x63reate\x12\".personservice.CreatePersonRequest\x1a#.personservice.CreatePersonResponse\x12K\n\x06select\x12\x1f.personservice.GetPersonRequest\x1a .personservice.GetPersonResponse\x12Q\n\x06update\x12\".personservice.UpdatePersonRequest\x1a#.personservice.UpdatePersonResponse\x12Q\n\x06remove\x12\".personservice.DeletePersonRequest\x1a#.personservice.DeletePersonResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON']._serialized_start=31
  _globals['_PERSON']._serialized_end=108
  _globals['_CREATEPERSONREQUEST']._serialized_start=110
  _globals['_CREATEPERSONREQUEST']._serialized_end=170
  _globals['_CREATEPERSONRESPONSE']._serialized_start=172
  _globals['_CREATEPERSONRESPONSE']._serialized_end=233
  _globals['_GETPERSONREQUEST']._serialized_start=235
  _globals['_GETPERSONREQUEST']._serialized_end=265
  _globals['_GETPERSONRESPONSE']._serialized_start=267
  _globals['_GETPERSONRESPONSE']._serialized_end=325
  _globals['_UPDATEPERSONREQUEST']._serialized_start=327
  _globals['_UPDATEPERSONREQUEST']._serialized_end=387
  _globals['_UPDATEPERSONRESPONSE']._serialized_start=389
  _globals['_UPDATEPERSONRESPONSE']._serialized_end=450
  _globals['_DELETEPERSONREQUEST']._serialized_start=452
  _globals['_DELETEPERSONREQUEST']._serialized_end=485
  _globals['_DELETEPERSONRESPONSE']._serialized_start=487
  _globals['_DELETEPERSONRESPONSE']._serialized_end=526
  _globals['_PERSONSERVICE']._serialized_start=529
  _globals['_PERSONSERVICE']._serialized_end=870
# @@protoc_insertion_point(module_scope)
